### ISSUE TITLE
Simplify categorization

### ISSUE THREAD

**Issue by brillout** [vuejs/awesome-vue#1049]
The current categorization is great for finding libraries.
But many PRs are put into the "wrong" category.
I've an idea for improving the situation. I'll post it here once it's more fleshed out. (It doesn't involve any third party tool.)

**Comment by Scrum** [comment]
@brillout I am ready to consider your proposal if it is and is still relevant

**Comment by brillout** [comment]
Hi Ivan, I'm super busy with other things and I won't have time to further work on Awesome Vue. Unfortunately :-(.

Feel free to close this ticket.
