### ISSUE TITLE
Can I add my new Vue2.0 project to awesome-vue project list?

### ISSUE THREAD

**Issue by 016** [vuejs/awesome-vue#1092]
Hey All, I just built one SPA online tool system by VueJS 2.0, is it possible that I can add my new project the "Apps/Websites" category?

FYI:
Name: iTool
URL: itool.yiilib.com
Decs: Online SPA Tool system build with VueJS 2.0 and Yii 2.0

thx.

**Comment by DannyFeliz** [comment]
Of course you can, just make sure to follow the [Contributing Guide](https://github.com/vuejs/awesome-vue/blob/master/CONTRIBUTING.md)

**Comment by Scrum** [comment]
@016 Do you still need help?
