### ISSUE TITLE
Suggestion: Add Vue-loop

### ISSUE THREAD

**Issue by cjblomqvist** [vuejs/awesome-vue#1098]
Possible addition. Post on HackerNews today and seems to work awesomely ;-)

https://github.com/lookstudios/vue-loop

**Comment by cjblomqvist** [comment]
(sorry for not posting PR, due to lack of time this wasn't possible). If rejected it's totally fine.

**Comment by Blaked84** [comment]
Il was solved in #1096 :-)

**Comment by cjblomqvist** [comment]
:-)
