### ISSUE TITLE
Plugin was removed ( require-vuejs )

### ISSUE THREAD

**Issue by edgardleal** [vuejs/awesome-vue#1244]
I saw that the plugin `require-vuejs` ( created for me ) was removed in commit b6296be86fed0de3ed238aa5398ae6f068d60a24.

There are any reason for this ?
There are any thing that a can do to solve it?

**Comment by nickmessing** [comment]
@edgardleal, I think at that time it was breaking some of the rules, probably it was considered `unmaintained` or it was not supporting Vue 2.0. I am sorry if that's not true and if it respects the rules feel free to add it again.

**Comment by edgardleal** [comment]
Ok. Thank you for feedback. Can you send me the link of these rules?

**Comment by edgardleal** [comment]
I found it here [https://github.com/vuejs/awesome-vue/blob/master/CONTRIBUTING.md](CONTRIBUTING.md).
I will check all the rules and if the plugin don´t breaking any of these rules, I will send a new pull request.

**Comment by edgardleal** [comment]
A created a pullrequest https://github.com/vuejs/awesome-vue/pull/1303 and I will wait for merge.
