### ISSUE TITLE
Add REAM

### ISSUE THREAD

**Issue by qm3ster** [vuejs/awesome-vue#1322]
As far as I could see, [REAM (*ream.js.org*)](https://ream.js.org) is missing.
It should probably be featured alongside Nuxt.js, which perhaps also deserves a more prominent spot.

**Comment by egoist** [comment]
I will send a PR.

**Comment by Scrum** [comment]
@qm3ster Please create a PR if this is still relevant

**Comment by qm3ster** [comment]
@Scrum deprecated in favor of https://vapperjs.org/
@egoist lol
