### ISSUE TITLE
Can we provide links for paid products?

### ISSUE THREAD

**Issue by lorvent** [vuejs/awesome-vue#1381]
Hello,

Can we provide links for paid product?

thanks

**Comment by ricky11** [comment]
agree, for this to be 'awesome' this repo should indicate weather the tut is free or paid or sponsored.

Ricky11

**Comment by Scrum** [comment]
@lorvent 
Can we provide links for paid product?

I think that with an explicit indication in the link - this will not contradict the rules.

@LinusBorg What do you think about this ?

**Comment by LinusBorg** [comment]
So far we haven't included any paid services as far as I'm aware. Those would not fit well under The two major categories, "Open Source" and "Apps/Websites".

If we had intended for paid content to be included, you would certainly find VueSchool or VueMastery on this list - but they are not.

So I don't think we want to start adding commercial services like Vue courses etc. to the list.

A commercial product *using* Vue would fit into the "Apps/Websites" category, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier would be fine in my opinion).

**Comment by Scrum** [comment]
@lorvent I have made changes in the attitude of commercial products https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md
