### ISSUE TITLE
Unmainteined libraries

### ISSUE THREAD

**Issue by mariomka** [vuejs/awesome-vue#1489]
What happens in this case? Should we remove it from the list or just add a note?

By example, vue-datepicker is unmaintained hilongjw/vue-datepicker#124 since January. Even npm package isn't up to date hilongjw/vue-datepicker#115 hilongjw/vue-datepicker#102 hilongjw/vue-datepicker#109.

**Comment by zazk** [comment]
We can use a note for each one that wasn't update for at least 6 months.

**Comment by Scrum** [comment]
@mariomka resolve in https://github.com/vuejs/awesome-vue/pull/1772
