### ISSUE TITLE
Add getlessons.com

### ISSUE THREAD

**Issue by ghost** [vuejs/awesome-vue#1647]
Hello! Add, please [getlesssons.com](https://getlessons.com). This is an example of a site fully working on vue 2.

**Comment by AlvinOrz** [comment]
This appears to be an orphaned link.  Did you spell it correctly?

**Comment by nobodywithbody** [comment]
Sorry. This is correct link https://get-lessons.com

**Comment by Scrum** [comment]
@ghost Please create a PR if this is still relevant
