### ISSUE TITLE
webpack: Failed to compile. Does Vue need Python 2.7 to build?

### ISSUE THREAD

**Issue by henon** [vuejs/awesome-vue#1700]
Below my install and start log with clean a install of npm. It fails to start. What am I doing wrong?

E:\>cd vue-admin-master

E:\vue-admin-master>npm -v
5.5.1

E:\vue-admin-master>node -v
v8.9.1

E:\vue-admin-master>npm install
npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we re
commend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the
'mapbox-gl-style-spec' package
npm WARN deprecated mapbox-gl-function@1.3.0: This package has been merged with
the 'mapbox-gl-style-spec' package
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install
@mapbox/point-geometry instead
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox names
pace: install @mapbox/shelf-pack instead
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namesp
ace: install @mapbox/whoots-js instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @ma
pbox/vector-tile instead
npm WARN deprecated unitbezier@0.0.0: This module has moved: switch to @mapbox/u
nitbezier
npm WARN deprecated husl@5.0.3: Project renamed to HSLuv
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox nam
espace: install @mapbox/geojson-area instead

> node-sass@3.13.1 install E:\vue-admin-master\node_modules\wysiwyg.css\node_mod
ules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.1
3.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win
32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.7.2 install E:\vue-admin-master\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7
.2/win32-x64-57_binding.node
Download complete  ] - :
Binary saved to E:\vue-admin-master\node_modules\node-sass\vendor\win32-x64-57\b
inding.node
Caching binary to C:\Users\Henon\AppData\Roaming\npm-cache\node-sass\4.7.2\win32
-x64-57_binding.node

> node-sass@3.13.1 postinstall E:\vue-admin-master\node_modules\wysiwyg.css\node
_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\vue-admin-master\node_modules\node
-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsas
s_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\vue-admin-master\\node_modules\\node-gyp\\bin\\node-gyp.js',

gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\vue-admin-master\node_module
s\which\which.js:13:12)
gyp verb `which` failed     at F (E:\vue-admin-master\node_modules\which\which.j
s:68:19)
gyp verb `which` failed     at E (E:\vue-admin-master\node_modules\which\which.j
s:80:29)
gyp verb `which` failed     at E:\vue-admin-master\node_modules\which\which.js:8
9:16
gyp verb `which` failed     at E:\vue-admin-master\node_modules\isexe\index.js:4
2:5
gyp verb `which` failed     at E:\vue-admin-master\node_modules\isexe\windows.js
:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\vue-admin-master\node_module
s\which\which.js:13:12)
gyp verb `which` failed     at F (E:\vue-admin-master\node_modules\which\which.j
s:68:19)
gyp verb `which` failed     at E (E:\vue-admin-master\node_modules\which\which.j
s:80:29)
gyp verb `which` failed     at E:\vue-admin-master\node_modules\which\which.js:8
9:16
gyp verb `which` failed     at E:\vue-admin-master\node_modules\isexe\index.js:4
2:5
gyp verb `which` failed     at E:\vue-admin-master\node_modules\isexe\windows.js
:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundE
rror (E:\\vue-admin-master\\node_modules\\which\\which.js:13:12)\n    at F (E:\\
vue-admin-master\\node_modules\\which\\which.js:68:19)\n    at E (E:\\vue-admin-
master\\node_modules\\which\\which.js:80:29)\n    at E:\\vue-admin-master\\node_
modules\\which\\which.js:89:16\n    at E:\\vue-admin-master\\node_modules\\isexe
\\index.js:42:5\n    at E:\\vue-admin-master\\node_modules\\isexe\\windows.js:36
:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Henon\AppData\Local\Programs\Python\P
ython36-32\python.EXE
gyp verb check python version `C:\Users\Henon\AppData\Local\Programs\Python\Pyth
on36-32\python.EXE -c "import platform; print(platform.python_version());"` retu
rned: "3.6.0\r\n"
gyp verb could not find "C:\Users\Henon\AppData\Local\Programs\Python\Python36-3
2\python.EXE". checking python launcher
gyp verb could not find "C:\Users\Henon\AppData\Local\Programs\Python\Python36-3
2\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Henon\AppData\Local
\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\vue-admin-master\node_module
s\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\vue-admin-master\node_modules
\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\vue-admin-master\node_modules\graceful-fs\polyfills.js:
284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\vue-admin-master\\no
de_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "
--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\vue-admin-master\node_modules\wysiwyg.css\node_modules\node-sass

gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN Error: EPERM: operation not permitted, scandir 'E:\vue-admin-master\nod
e_modules\wysiwyg.css\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'E:\vue-admin-master\
node_modules\wysiwyg.css\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'E:\\vue-admi
n-master\\node_modules\\wysiwyg.css\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'E:\\vue-admin-master\\node_modules\\wysiwyg.css\\node_modules'
 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Henon\AppData\Roaming\npm-cache\_logs\2017-11-27T20_49_39_
006Z-debug.log

E:\vue-admin-master>npm run dev

> vue-admin@0.1.12 dev E:\vue-admin-master
> cross-env NODE_ENV=development node build/dev-server.js

[HPM] Proxy created: /MODApis  ->  http://dev.markitondemand.com
webpack: wait until bundle finished:
webpack: wait until bundle finished: /index.html
webpack built aae45f5ad2d79f839235 in 17981ms
Hash: aae45f5ad2d79f839235
Version: webpack 2.7.0
Time: 17981ms
                                                 Asset     Size         Chunks
Chunk Names
                                                 15.js  65.6 kB             15

               assets/img/emojione.sprites.a44e653.svg  3.16 MB

  assets/fonts/materialdesignicons-webfont.f540b42.eot   275 kB

  assets/fonts/materialdesignicons-webfont.292b2f8.ttf   274 kB

assets/fonts/materialdesignicons-webfont.7f88c63.woff2   104 kB

 assets/fonts/materialdesignicons-webfont.c28dbba.woff   135 kB

                                                  0.js  19.2 MB              0

                                                  1.js  2.48 MB              1

                                                  2.js  2.48 MB              2

                                                  3.js  2.48 MB              3

                                                  4.js  90.6 kB  4, 12, 13, 14

                                                  5.js   154 kB              5

                                                  6.js   342 kB              6

                                                  7.js   106 kB              7

                                                  8.js   121 kB              8

                                                  9.js   213 kB              9

                                                 10.js  90.6 kB             10

                                                 11.js  65.9 kB             11

                                                 12.js  51.2 kB             12

                                                 13.js  46.3 kB             13

                                                 14.js  47.5 kB             14

    assets/img/materialdesignicons-webfont.633c9b8.svg  2.09 MB

                                                 16.js  1.62 MB             16

                                                 17.js  1.22 MB             17

                                                 18.js   540 kB             18

                                                 19.js   378 kB             19

                                                 20.js  46.9 kB             20

                                                 21.js  92.7 kB             21

                                                 22.js  41.2 kB             22

                                                 23.js  52.2 kB             23

                                                 24.js  53.1 kB             24

                                                 25.js  31.9 kB             25

                                                 26.js  15.6 MB             26

                                                 27.js  36.9 kB             27

                                                 28.js  38.3 kB             28

                                                 29.js  35.2 kB             29

                                                 30.js  43.8 kB             30

                                                 31.js  12.7 kB             31

                                                 32.js  6.24 kB             32

                                                 33.js  6.02 kB             33

                                                app.js   783 kB             34
app
                                             vendor.js  1.15 MB             35
vendor

ERROR in ./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-37fa8aa7
","scoped":false,"hasInlineConfig":true}!./~/sass-loader/lib/loader.js!./~/vue-l
oader/lib/selector.js?type=styles&index=0!./client/App.vue
Module build failed:
undefined
^
      File to import not found or unreadable: ~wysiwyg.css/wysiwyg.sass.
Parent style sheet: stdin
      in E:\vue-admin-master\client\App.vue (line 65, column 1)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"
data-v-37fa8aa7","scoped":false,"hasInlineConfig":true}!./~/sass-loader/lib/load
er.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./client/App.vue 4:14-3
03 13:3-17:5 14:22-311
 @ ./client/App.vue
 @ ./client/app.js
 @ ./client/index.js
 @ multi ./build/dev-client ./client/index.js
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.48 MB       0
webpack: Failed to compile.
> Listening at http://localhost:8080

**Comment by henon** [comment]
I had python 3.6 installed by the way. after installing Python 2.7 

 npm install

runs through and the app is starable.  Maybe this should be noted somewhere? in development.md for instance?

**Comment by DannyFeliz** [comment]
This repo doesn't have anything to do with your issue

**Comment by henon** [comment]
I know, not directly. Some component obviously needs Python. So if Python is not installed, this project fails to build. 

So why not state all the dependencies of the project somewhere obvious?

**Comment by sodatea** [comment]
You need Python and a C++ to be able to compile native modules.
Normally node-sass fetches the binary for you, if you are on a supported platform. But if it's failed, you'll need to compile them manually, which is why Python is required here.
Anyway, it has nothing to do with vue.

**Comment by henon** [comment]
Thanks for the clarification and thanks for this project! It really helped me discover how awesome Vue really can be.
