### ISSUE TITLE
Add AutoTube - the all in one youtube player that you never knew you needed

### ISSUE THREAD

**Issue by ahadcove** [vuejs/awesome-vue#1745]
https://auto-tube.com

AutoTube is the all in one youtube player that you never knew you needed. Made with Vue.
Ever wondered why youtube hasn't implemented certain features like being able to make a playlist of your subscriptions newest videos in a click of a button? Me too, that's why I created AutoTube. Spend less time making playlists and more on your work!
Build a playlist of your subscriptions newest videos with a click

Category: App/Websites

**Comment by ankurk91** [comment]
You can submit a PR

**Comment by Scrum** [comment]
@AhadCove Please create a PR if this is still relevant
