### ISSUE TITLE
vue有类似支持这种画布的组件吗

### ISSUE THREAD

**Issue by caizhihuan** [vuejs/awesome-vue#1769]
![image](https://user-images.githubusercontent.com/6183352/34438895-eb3614a0-ece4-11e7-8156-34d3467849c6.png)

**Comment by caizhihuan** [comment]
help

**Comment by ankurk91** [comment]
This repo is not for such issues. Please consider public forums for support.
https://forum.vuejs.org/

**Comment by caozhong1996** [comment]
upper post is right.

**Comment by Scrum** [comment]
@caizhihuan Please respect the rest of the participants, use English
