### ISSUE TITLE
visibility of component collections

### ISSUE THREAD

**Issue by paulpflug** [vuejs/awesome-vue#180]
in commit https://github.com/vuejs/awesome-vue/commit/3ef3ba380f0ca0cd6a852bd463405d7df9f9a3f0
I moved some of my components into a component collection. Since then they suffer from reduced visibility.

The collection currently is 23 components big, I don't want to flood the list with all of them.

So here is my proposal: make an extra section with component collections (all the material/bootstrap repos) and allow to expose some of the most important included components:

like this:

### Component collections
- [vue-comps](https://github.com/vue-comps) a collection of unstyled vue-components
  * [vue-clusterize](https://github.com/vue-comps/vue-clusterize) Invisible pagination
  * [vue-parallax](https://github.com/vue-comps/vue-parallax) Scrolls a image slower than the window to create a neat optical effect
- other collections

what do you think?

**Comment by yyx990803** [comment]
Sounds good to me!
