### ISSUE TITLE
Add bages or even reformat list to table with availability sorting.

### ISSUE THREAD

**Issue by Koc** [vuejs/awesome-vue#1853]
It is hard to choose most popular library now. For example there are 9 libraries for local storage. I want to decide which is most popular, still maintaned, etc.

Would be nice add github badges with stars/issues/PR counts to list of available libraries using service like https://github.com/ddavison/github-badges or any other. Availability of this kind of information saves time when you searching for new library.

Not sure, is adding badges for large list is good idea (it can cause too much http requests). Maybe use api for aggregating data from repos and cache it. But it requires more efforts and separate site.

**Comment by nicholaslee119** [comment]
Agree with that, 
Indeed, It is really hard to choose in a large text plain list

**Comment by Scrum** [comment]
@Koc Good idea, we will consider it.

**Comment by Koc** [comment]
@Akryum created site for that https://awesomejs.dev/ , so this issue is not actual anymore
