### ISSUE TITLE
Add vue-moment ?

### ISSUE THREAD

**Issue by SayedShahidi** [vuejs/awesome-vue#1884]
https://github.com/brockpetrie/vue-moment

**Comment by ankurk91** [comment]
PR welcome

**Comment by Scrum** [comment]
@SayedShahidi Please create a PR if this is still relevant

**Comment by Jogai** [comment]
[You Dont Need Momentjs](https://github.com/you-dont-need/You-Dont-Need-Momentjs) :wink:
