### ISSUE TITLE
Add a xdraggable as a drag and drop library

### ISSUE THREAD

**Issue by TimYi** [vuejs/awesome-vue#1940]
[xdraggable](https://github.com/shaoxiong789/vue-xdraggable) seems a good drag and drop library. It's a vue2 component for draggable and resizable elements.

It's demo link: [demo](https://shaoxiong789.github.io/vue-xdraggable/demo/dist/)

**Comment by saintplay** [comment]
Vue2 component for draggable **and resizable elements**

It supports resize?

**Comment by TimYi** [comment]
@saintplay I have not seen it's resize demo, It's drag demo seems good.

**Comment by TimYi** [comment]
Not very useful, worse than vue-draggable-resizable.
