### ISSUE TITLE
 Reclassify the list by VUE's version, now it classify by function.能否 根据 VUE 的 版本 来 将 资源 重新分一下类呢？

### ISSUE THREAD

**Issue by Jerry-goodboy** [vuejs/awesome-vue#1962]
English:
Reclassify the list by VUE's version, now it classify by function.

中文：
现在 都是 基于 功能 分的类，那么 能否 在此基础上 再在 版本上面 细分出 资源呢，因为 有些资源 版本2 根本 用不了，这样 试错的 成本 太大了，希望 采纳，谢谢

**Comment by nicholaslee119** [comment]
你好，请用英文描述你的问题。
Hi, please describe your issue in English, 
So your issue can be discussed by the most people in our community.

**Comment by Scrum** [comment]
@Jerry-goodboy It is not clear what you mean, describe in more detail if this is still relevant to you
