### ISSUE TITLE
Suggestions and improvements? 

### ISSUE THREAD

**Issue by omarsotillo** [vuejs/awesome-vue#2021]
First of all congrats for the awesome repo! 👍 
But so far I have seen the following problems whenever I come here to inspect new thingies :)

**Suggestions**: 
- In tutorial more subparts are needed. What I see is a bloated huge list of a mix of tutorials nonsense and non related. So we could have the following parts (example) Vue general, vuex, weex, vue router, styles...etc This should be determined beforehand. The same with examples.
- I would reorder the real apps, example apps using of vue.js and demos to the end. I think this is the most optional and less interesting part of the awesome list somehow.
- Also I would love seeing clear parts of the most important plugins like React awesome has. Better organization of the parts and a smaller index list I think is needed.
- Maybe we could have tags identifying different versions of Vue.js like 2.0 (just major releases though) in each post for the components. Most of the times you have to go inside the repo to see what they are about and also a standard format of the component nomenclature and description.
- I see many many many plugins and components totally outdated and non maintained in the list. I am not saying all should be deleted but maybe some kind of selective delete should be done.
- Having a clear and simple contribution guide.

Best regards,
Omar 😄

**Comment by DannyFeliz** [comment]
@omarsotillo Cool bro, but who is going to maintains all these stuff?
