### ISSUE TITLE
add v-page

### ISSUE THREAD

**Issue by TerryZ** [vuejs/awesome-vue#2060]
Github repo: [https://github.com/TerryZ/v-page](https://github.com/TerryZ/v-page)

Website
- [https://terryz.github.io/vue/#/](https://terryz.github.io/vue/#/)
- [https://terryz.oschina.io/vue/#/](https://terryz.oschina.io/vue/#/)

Category: UI Utilities / Pagination

**Comment by kazupon** [comment]
You can add the PR :)
