### ISSUE TITLE
Add Vuetify's Datepicker

### ISSUE THREAD

**Issue by oiagorodrigues** [vuejs/awesome-vue#2070]
Hi. 
I know that it's already recommended **Vuetify** on this list, but I think that it would be a great addition to the **Datepicker** section to add the _[vuetify's datepicker component](https://vuetifyjs.com/en/components/date-pickers)_ into this section.

Let me know of your opinion about the suggestion.

iago

**Comment by Scrum** [comment]
@oiagorodrigues Please create a PR if this is still relevant
