### ISSUE TITLE
Add vue-cloneya

### ISSUE THREAD

**Issue by ridaamirini** [vuejs/awesome-vue#2135]
https://github.com/ridaamirini/vue-cloneya

Category: UI Components/Miscellaneous

**Comment by kazupon** [comment]
close due to merged it

**Comment by runchicken** [comment]
mute the thread

At 2018-05-18 23:11:35, "Rida Amirini" <notifications@github.com> wrote:


https://github.com/ridaamirini/vue-cloneya

Category: UI Components/Miscellaneous
