### ISSUE TITLE
Add vue-svgicon

### ISSUE THREAD

**Issue by dnhyde** [vuejs/awesome-vue#2156]
Catergory: [Awesome-vue Icon](https://github.com/vuejs/awesome-vue#icons)

While [vue-awesome](https://github.com/Justineo/vue-awesome) is great and I used and loved it. To have more icons (convert automatically from svg to component) [vue-svgicon](https://github.com/MMF-FE/vue-svgicon) is a great option! 

Read [this blog](https://alligator.io/vuejs/using-svg-icons/) if you are still not convinced. Moreover read carefully what you should do **first of all**! For example, my icons were not inheriting colors because I was in a hurry and missed [this step](https://github.com/MMF-FE/vue-svgicon#use-generated-icon)

**Comment by Scrum** [comment]
@dnhyde Please create a PR if this is still relevant

**Comment by dnhyde** [comment]
Just noticed it is present under [SVG](https://github.com/vuejs/awesome-vue/blob/master/README.md#svg) but not under [Icons](https://github.com/vuejs/awesome-vue/blob/master/README.md#icons). Maybe it should be moved under icons, I will create the PR if you agree

**Comment by Scrum** [comment]
@dnhyde agree
