### ISSUE TITLE
use $mount() to manual mounted a component, the component's event and data-binding doesn't work

### ISSUE THREAD

**Issue by DLJames** [vuejs/awesome-vue#2225]
Case：
parent component：
```
<script>
import Vue from 'vue'
import Demo1 from '../demo1'

let demoComponent = Vue.extend(Demo1)
export default {
  name: 'HelloWorld',
  data () {
    return {
      msg: 'Welcome to My Vue.js Demo App'
    }
  },

  mounted () {
    let cp  = new demoComponent({
      propsData: {name: 'xiao ming'}
    })
    cp.$mount()
    let msg = cp.$el.outerHTML
    this.$el.innerHTML = msg
  }
}
</script>
```

in child component demo1.vue, the click event and data binding doesn't，how to make it work?

child component:
```
<template>
<div>
    <p>This is vue demo1</p>
    <input v-model="msg">
    {{msg}}     <!-- not work -->
    <button @click="showme">submit</button>
</div>
</template>
<script>
export default {
    data () {
        return {msg:  'ni hao' }
    },
    mounted () {},
    methods: {
        showme (evt) {
            console.log('evt=', evt.target) //not work
        }
    }
}
</script>
```
If you ask me why I did it like that, cuz I used a third library chat-ui, https://github.com/artemdemo/chat-ui to generate a chat dialog tool, so I have to invoke the method that chat-ui offered "eg：this.chat.trigger('add-phrase', {'chat', innerHTML})", so I have to pass the innerHTML to chat-ui to ask it help to create a dialog message, otherwise I have no idea.

**Comment by Scrum** [comment]
@DLJames I do not think that this question is better to ask in this repository, try to do it in https://github.com/vuejs/vue
