### ISSUE TITLE
Add vue-graph (Category: Charts)

### ISSUE THREAD

**Issue by seogi1004** [vuejs/awesome-vue#2281]
A vue plug-in that makes charting easy.

The project links are: [GitHub](https://github.com/juijs/vue-graph) [Examples](https://codepen.io/collection/nWpqoB/)

The vue-graph plug-in is based on the JUI chart: [GitHub](https://github.com/juijs/jui-chart) [Examples](http://jui.io/?p=chart) [Gallery](http://jui.io/?p=gallery)

I have migrated a very small part of it yet, but I will continue to develop it in the future.

**Comment by Scrum** [comment]
@seogi1004 Please create a PR if this is still relevant
