### ISSUE TITLE
Link not work

### ISSUE THREAD

**Issue by skar404** [vuejs/awesome-vue#2292]
### Status code list:
 - 404:
     - https://github.com/nikitamarcius/vue-markdown
     - https://addons.mozilla.org/en-US/firefox/addon/mechmod/
     - https://halfeld.github.io/v-notes/#!/ -> https://github.com/IgorHalfeld/v-notes
     - https://github.com/MisRob/Justine
     - http://forum.vuejs.org/topic/39/starter-application-with-jwt-auth-sample-backend-api

 - 500:
	 - https://vulma.org
	 - https://check-it.io
	 - https://app.xiaotaojiang.com/
	 - https://vuejs-korea.signup.team/

> automatic check

**Comment by Bitti09** [comment]
https://halfeld.github.io/v-notes/#!/ seems to be  now  here: https://github.com/IgorHalfeld/v-notes

Intro.js works for me

**Comment by Scrum** [comment]
@skar404 thanks,  resolved in #2943
