### ISSUE TITLE
Please add VueMastery

### ISSUE THREAD

**Issue by ChaseWGregory** [vuejs/awesome-vue#2313]
Vue Mastery has been doing a lot for the Vue community and I will like to see it in this awesome list in a couple of different Categories. 

Please add a sub-link to VueConfUS for all of the previously recorded talks at the conference.
https://www.vuemastery.com/vueconf?utm_campaign=vue-conf&utm_medium=github&utm_source=vue-awesome

Please also add this "Intro to Vue" free course by Adam Jahr
https://www.vuemastery.com/courses/intro-to-vue-js/vue-instance?utm_campaign=Intro-course&utm_medium=github&utm_source=vue-awesome

Add to Websites
https://www.vuemastery.com/?utm_campaign=homepage&utm_medium=github&utm_source=vue-awesome

As a YouTube Channel for all the 30+VueConf.US talks.
Here is the playlist for the conference.
https://www.youtube.com/watch?v=j1EWDbXtbjA&list=PLJNLwTPak6dj-HOz4eFrKDJsJSZsgvWPs&index=1

Lastly, the Vue Essentials Syntax Cheat-Sheet
https://www.vuemastery.com/vue-cheat-sheet?utm_campaign=cheat-sheet&utm_medium=github&utm_source=vue-awesome

Thank you in advance!

**Comment by Scrum** [comment]
@ChaseWGregory Please create a PR if this is still relevant
