### ISSUE TITLE
Is there a way to view by date added?

### ISSUE THREAD

**Issue by notchris** [vuejs/awesome-vue#2359]
Sorry if this is a silly question, can we see a list of the most recently posted items? Half of the libraries are outdated and it would be cool to focus on the ones that stayed updated.

**Comment by Justineo** [comment]
I’ m afraid the answer is no ATM. It’s just a plain Markdown file. And although many of the project are outdated or even abandoned, sorting them by the time added is not necessarily reasonable. There are still quite a few projects added long ago still being actively maintained. You can also check our [curated list](https://curated.vuejs.org) to learn projects with top quality in the ecosystem.

**Comment by notchris** [comment]
That makes sense, thank you!
