### ISSUE TITLE
Add vue-tree-nav on menu category

### ISSUE THREAD

**Issue by marcodpt** [vuejs/awesome-vue#2368]
First of all, thanks a lot for this awesome list 

I am the owner of this project

https://github.com/marcodpt/vue-tree-nav

with this live demo

https://marcodpt.github.io/vue-tree-nav/

the main reason why I create this project is that none of the menu on this list 

https://github.com/vuejs/awesome-vue#menu

satisfied me. I need a menu with easy vue-router integration for quick use in my open source projects and I need flexible layouts to use in production.

I really think I am giving some good menu option to community, and I really think community can help me improve the menu

Thanks a lot

**Comment by Scrum** [comment]
@marcodpt Please create a PR if this is still relevant
