### ISSUE TITLE
Add vue-termini

### ISSUE THREAD

**Issue by Mikepicker** [vuejs/awesome-vue#2421]
vue-termini is a simple & lightweight (css-only animation) animated terminal frame for vue projects.
It's super easy to setup and embed.

Repo: https://github.com/Mikepicker/vue-termini

![termini](https://raw.githubusercontent.com/Mikepicker/vue-termini/master/termini.gif)

Thank you!

**Comment by Scrum** [comment]
@Mikepicker Please create a PR if this is still relevant
