### ISSUE TITLE
Is your website mining coins?

### ISSUE THREAD

**Issue by arenasv86** [vuejs/awesome-vue#2469]
Hi,
I've visited your website a lot of times. But the last one, my CPU usage turns up up to 700%. I started to close Chrome tabs and then reenter  in your site. My computer fans started to work at 200%.
Then I take a look to the Sources tab in Chrome and I can see the coinhive script for mining cryptocoins.

I'm not sure if its a mistake but honestly, I don't think is kind of things is right for a project like this.

![captura de pantalla 2018-10-15 a las 11 54 33](https://user-images.githubusercontent.com/581171/46944138-96854b80-d071-11e8-9161-946289c2a881.png)

**Comment by wilsonpinto** [comment]
@arenasv86 What website? Github ?

**Comment by Jigsaw5279** [comment]
Which website did you visit? I can't seem to find that script

**Comment by LinusBorg** [comment]
`awesome-vue` doesn'T have its own website, and github doesn't include coinhive - and if it did, that would not be our fault or responsibility, we are not Github.
