### ISSUE TITLE
Inaccessible component libraries

### ISSUE THREAD

**Issue by callumacrae** [vuejs/awesome-vue#2586]
A lot of the component libraries linked to in this list are inaccessible, meaning that people using them on their projects may be inadvertently making their sites inaccessible.

I'd propose adding something to the contributing guide saying that libraries must be accessible to be accepted, and possibly removing existing ones that are inaccessible.

I'm always happy to test libraries and give library authors advice on how to make them accessible :)

**Comment by kazupon** [comment]
I also feel that there is a limit in the maintenance.
In order to eliminate it, I think that we need tools in awesome-vue.
Unfortunatly, I have no idea. 😞

**Comment by callumacrae** [comment]
Tools won't really help for most of the issues I've found with existing components, most of them I found through manual inspection or testing with a screenreader.

Perhaps it could be a soft rule - you could add it to the contributing guide and give people a couple days to test projects when PRs are sent, but if nobody says anything just merge anyway.

**Comment by kazupon** [comment]
Thank you for your adivise!
I see. :)
How do I let people know the library of PR?
Vue-Land?

**Comment by callumacrae** [comment]
That could work - there's an #accessibility channel which we could use.

Also, could just watch the repo.

**Comment by codebender828** [comment]
I'm fairly new to accessibility and have never learned before about it, but I'd like to help. Anything that I can do? I could start by learning what it is and how it is used.

**Comment by Scrum** [comment]
@callumacrae add more information on 
[contributing](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md)
[pull_request_template](https://github.com/vuejs/awesome-vue/blob/master/.github/pull_request_template.md)

there is also the task of eliminating dead links #2943
