### ISSUE TITLE
Link is dead.

### ISSUE THREAD

**Issue by musicformellons** [vuejs/awesome-vue#261]
Link to:
SPA Blog Personal blog and portfolio site see repository

does not work.

**Comment by ktquez** [comment]
Thank you for letting @simplesmiler 
I had a problem to renew, I believe that will be available again until this weekend

**Comment by ktquez** [comment]
I'm temporarily using this Surge (http://ktquez.surge.sh/), you want me to change there until I come back to the area air?

**Comment by ktquez** [comment]
Already sent a PR to update temporarily until the problem has been solved, once it is mixed, is pointing to an online site.

Thanks a lot

**Comment by simplesmiler** [comment]
Merged, feel free to send PR when the link is back up again.
