### ISSUE TITLE
[ ADD ] LazyDrive Written in Vue.js and Node.js to manage media file with api endpoint. 

### ISSUE THREAD

**Issue by Anu1601CS** [vuejs/awesome-vue#2725]
LazyDrive Written in Vue.js and Node.js to manage media file with API endpoint supports Dropbox, Google Drive currently.

A great tool to manage media file on your server and use in your application.  

Repo: https://github.com/lazyDrive/drive

Its open source and contributions are welcome. :)

**Comment by Scrum** [comment]
@Anu1601CS Please create a PR if this is still relevant

**Comment by Anu1601CS** [comment]
@Scrum yeah sure
