### ISSUE TITLE
Add vue-menu-aim

### ISSUE THREAD

**Issue by Dimon24021993** [vuejs/awesome-vue#2887]
Please add vue-menu-aim 

It's add amazon triangle to menu select

https://github.com/Dimon24021993/vue-menu-aim
https://www.npmjs.com/package/vue-menu-aim

(:

**Comment by DannyFeliz** [comment]
This does not work like this, you have to folk this repo and send a pull request including you package in the corresponding section.

**Comment by Scrum** [comment]
@Dimon24021993 Please create a PR if this is still relevant
