### ISSUE TITLE
Grid from parsing strings in examples (feature request)

### ISSUE THREAD

**Issue by janat08** [vuejs/awesome-vue#300]
I belief that example less so oriented towards view but rather towards control would be a table that transforms data into meaningful presentation rather than just serving organizational or aesthetic purpose.

A table that's composed of data that holds a string and number for example but has row and column header from parts of the string that hold commonality across several entries and within the corresponding cell hold 2nd part of information like a number.

Example:
Bad Apple: 3
Fair Apple: 2
Good Apple: 9
Fair Orange: 1
Good Orange: 6
Bad Haircut: 2

Upon being fed this data table construct columns for bad and fair, while row headers hold apples and oranges with cells holding numbers. It basically follows logic where most common denominator between all strings (adjective) becomes a column whereas nouns become a row with numbers being represented for each variation.

**Comment by LinusBorg** [comment]
This is not the Vuejs repository. Please post feature requests in the right repository (https://github.com/vuejs/vue/issues/)

Also, personally I don't understand your description of the desired feature.
