### ISSUE TITLE
add a category of WebAssembly

### ISSUE THREAD

**Issue by AndrusGerman** [vuejs/awesome-vue#3017]
WebAssembly is a great tool and some people add information on how to use it in Vuejs.
But there is no category in this list to add items related to WebAssembly
* [Call WebAssembly in Vue](https://medium.com/@brockreece/vue-webassembly-1a09e38d0389)  
* [VueGo - go wrapper to Vuejs](https://gitlab.com/AndrusGerman/vuego)  
* [vue-wasm -  NPM lib](https://www.npmjs.com/package/vue-wasm)

**Comment by Scrum** [comment]
@AndrusGerman Please create a PR if this is still relevant
