### ISSUE TITLE
404

### ISSUE THREAD

**Issue by cnryb** [vuejs/awesome-vue#3023]
Podcasts
	和 Vue.js 框架的作者聊聊前端框架开发背后的故事 [zh-CN]
404 Page not found

**Comment by Scrum** [comment]
@cnryb It works for me

**Comment by cnryb** [comment]
Take a look at the content of the open link, it says **Page not found**.

**Comment by Scrum** [comment]
Yes, I mixed it up with another project, according to your appeal, a task has already been instituted in https://github.com/vuejs/awesome-vue/pull/2943

**Comment by cnryb** [comment]
OK, thanks.
