### ISSUE TITLE
Add vue-search-panel

### ISSUE THREAD

**Issue by TheoXiong** [vuejs/awesome-vue#3102]
A Vue component for searching with suggestions
[https://github.com/TheoXiong/vue-search-panel](https://github.com/TheoXiong/vue-search-panel)

![image](https://user-images.githubusercontent.com/42533484/70627088-86aacc80-1c60-11ea-9b5a-03bf4759e40c.png)

**Comment by Scrum** [comment]
@TheoXiong Please create a PR if this is still relevant

**Comment by TheoXiong** [comment]
> @TheoXiong Please create a PR if this is still relevant

I have created a PR [#3116](https://github.com/vuejs/awesome-vue/pull/3116)，and it's merged.
Thank you.
