### ISSUE TITLE
Add Rapido

### ISSUE THREAD

**Issue by InfoLibre** [vuejs/awesome-vue#3104]
Could someone add Rapido in https://github.com/vuejs/awesome-vue#open-source ?

**Rapido** is software to make a website. Rapido is fast, easy to use and respectful of your privacy.
https://framagit.org/InfoLibre/rapido

**Comment by Scrum** [comment]
@InfoLibre Please create a PR if this is still relevant

**Comment by InfoLibre** [comment]
Done
