### ISSUE TITLE
Update Pull Request Template

### ISSUE THREAD

**Issue by Kazaf123** [vuejs/awesome-vue#3140]
It seems that a good choice to  update a Pull Request Template to make the pull request more readable. Such as:
######Description

######Check List

######My PR Type is:

Thank you!!

**Comment by mihaimaruseac** [comment]
Seems to be spam
![VCA6DzWKgeZ](https://user-images.githubusercontent.com/323199/72463619-84202300-3788-11ea-9d4b-08ac8683f524.png)
