### ISSUE TITLE
Squash listings under same brand

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/awesome-vue#320]
I noticed some components under same brand are listed independently which, IMHO, is just artificially fattening the list. I suggest we put an end to it before it becomes a **trend**.

If the brand is using independent repos for each subcomponent, which seems the main reason, it should list one main repo or site where the entire collection can be seen.

**Comment by brillout** [comment]
I believe we've addressed this issue with the refactor. Should we close the ticket?
