### ISSUE TITLE
Add vue-route-props

### ISSUE THREAD

**Issue by iendeavor** [vuejs/awesome-vue#3245]
vue-route-props provide that automatically bind vue-router query to vm, APIs are mostly same as the Vue props.

[playground](https://codesandbox.io/s/vue-route-props-vbuj1?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Scrum** [comment]
@iendeavor Please create a PR if this is still relevant

**Comment by iendeavor** [comment]
@Scrum thanks for review.😃
