### ISSUE TITLE
GitHub Actions failing for awesome-vue since the beginning?

### ISSUE THREAD

**Issue by hartwork** [vuejs/awesome-vue#3323]
Hi!

It looks like GitHub actions [have been failing](https://github.com/vuejs/awesome-vue/actions?query=workflow%3A%22Create+dataset%22) for this repository since they were first introduced. Are there plans to drop or fix the broken GitHub actions? It looks rather unfortunate on both master commits and pull request right now. What do you think?

Best, Sebastian

**Comment by Scrum** [comment]
Hi, at the moment there are not enough rights to fix this problem, I think this action will be deleted

**Comment by hartwork** [comment]
Thank you!
