### ISSUE TITLE
The Spice House is built with React not Vuejs

### ISSUE THREAD

**Issue by Ejiro-Asiuwhu** [vuejs/awesome-vue#3341]
[The Spice House ](https://www.thespicehouse.com/) is not a Vuejs application
![Screenshot (107)](https://user-images.githubusercontent.com/45228014/82487829-d1195a80-9ad6-11ea-94b4-208fb6ca5404.png)

**Comment by Scrum** [comment]
@Ejiro-Asiuwhu Thanks 👍

**Comment by Ejiro-Asiuwhu** [comment]
@Scrum is there anyway I could contribute. I have a list of awesome projects and products built with Vuejs

**Comment by Scrum** [comment]
@Ejiro-Asiuwhu We are always happy to make new contributions, do not hesitate to do PR
