### ISSUE TITLE
Suggestion: Add link to awesome-vue-3 list

### ISSUE THREAD

**Issue by blacksonic** [vuejs/awesome-vue#3370]
Hi, I'm the maintainer of a similar awesome list targeting only Vue 3. https://github.com/blacksonic/awesome-vue-3

My idea is to add a link to the Vue 3 specific list. This would solve the problem with articles/videos that will remain only Vue 2 compatible.

Let me know what do you think about it.

**Comment by Scrum** [comment]
I think this is a good idea.
