### ISSUE TITLE
图片剪裁处理工具VuePictureCut

### ISSUE THREAD

**Issue by 987153776** [vuejs/awesome-vue#3399]
**项目名称**：vue-picture-cut  

**子标题**: 基于vue和typescript开发的一款图片剪裁处理工具。  

**相关介绍**: 基于vue和typescript开发的一款图片剪裁处理工具。优点：原生、轻量、使用简单、功能全面、扩展性强。目前功能：缩放、翻折、旋转、边缘校验、矩形剪裁、任意(椭)圆剪裁。关于缩放：鼠标（鼠标滚轮缩放）、触屏（双指缩放）。  

[github主页](https://github.com/987153776/vue-picture-cut) [demo演示](https://light-year.gitee.io/vue-picture-cut/) [文档](https://github.com/987153776/vue-picture-cut/blob/master/README.md)

**Comment by Scrum** [comment]
@987153776 Please respect others, communicate in English

**Comment by xy163** [comment]
@987153776 your see your one Day 

> `Day,hhhhhhh.哈哈哈哈笑死我了```

**Comment by shentaibai** [comment]
笑死我了,你这神奇的不能用英文
