### ISSUE TITLE
Add Vue data dict

### ISSUE THREAD

**Issue by moxun1639** [vuejs/awesome-vue#3421]
通用的数据字典，不仅限于传统意义上的数据字典，可以将任意对象转换为标准的label-value形式对象，来为下拉列表提供数据源
同时可以方便的对一些字典值进行解释显示
https://github.com/moxun1639/vue-data-dict

**Comment by Scrum** [comment]
@moxun1639 Please contact in English respect other members

**Comment by moxun1639** [comment]
A general data dictionary for Vue.js
Unify dictionary data format, support lazy loading and value translation, provide data source for front-end components.
