### ISSUE TITLE
Add vue-ins-progress-bar

### ISSUE THREAD

**Issue by meloalright** [vuejs/awesome-vue#3423]
[vue-ins-progress-bar](https://github.com/meloalright/vue-ins-progress-bar) - A vue component of ins-style progress bar 一款 ins 风格的 vue 进度条组件

with 300+ ☆stars and 5k+ downloads in last 7 months this year

**Comment by Scrum** [comment]
feel free to create PR

**Comment by meloalright** [comment]
> feel free to create PR

#3424 THX
