### ISSUE TITLE
Suggestion: add @korijn/vue-store

### ISSUE THREAD

**Issue by Korijn** [vuejs/awesome-vue#3595]
Today I released a new library, `@korijn/vue-store`, a lightweight Vue 3 composition API-compatible store pattern library with undo/redo. You may want to list it here?

Library: https://github.com/Korijn/vue-store
Live demo: https://korijn.dev/vue-store-todo-app/index.html
Demo source: https://github.com/Korijn/vue-store-todo-app

I would open a PR myself but I'm not sure in which categories I should put it. Any suggestions?

**Comment by Jogai** [comment]
https://github.com/vuejs/awesome-vue#state-management
