### ISSUE TITLE
add vue-easy-form

### ISSUE THREAD

**Issue by chengaohe45** [vuejs/awesome-vue#3608]
docs: [https://chengaohe45.github.io/vue-easy-form-docs/dist/](https://chengaohe45.github.io/vue-easy-form-docs/dist/)

github: [https://github.com/chengaohe45/vue-easy-form](https://github.com/chengaohe45/vue-easy-form)

demo: [https://chengaohe45.github.io/vue-easy-form-docs/demo/#/](https://chengaohe45.github.io/vue-easy-form-docs/demo/#/)

**Comment by Scrum** [comment]
Feel free to create PR

**Comment by cannap** [comment]
you need also english docs  @chengaohe45
