### ISSUE TITLE
Add vue-fontawesome-autogen

### ISSUE THREAD

**Issue by GTANAdam** [vuejs/awesome-vue#3649]
https://github.com/GTANAdam/vue-fontawesome-autogen

**Comment by Jogai** [comment]
I think https://github.com/antfu/purge-icons might be more awesome :smile:

**Comment by GTANAdam** [comment]
> I think https://github.com/antfu/purge-icons might be more awesome 😄

It's basically the same thing but mine has the advantage of being much more straightforward for FontAwesome with less setup complexity.

So instead of having to use Iconify for adding icons, you just use the bundles of just Fontawesome which means less stuff to clutter code with.

Also the code is much straightforward. instead of writing (or rewriting to):
`<span class="iconify" data-icon="fa:home"></span>`
you just write
`<fa icon="fas-home" />`
and if you have noticed, purge-icons doesn't allow you the option to choose the type of icons (solid, regular, etc..) which is a huge disadvantage.

What makes this a better usage for FontAwesome is the fact that this doesn't require projects to rewrite their code, it will basically be a plug'n'compile instead of having to rewrite things.

**Comment by Jogai** [comment]
Well, that is awesome!

**Comment by GTANAdam** [comment]
> Well, that is awesome!
> 
> By the way, with purge icons you can still pick the type like:
> 
> ```
> <span class="iconify" data-icon="fa-regular:angry" data-inline="false"></span>
> <span class="iconify" data-icon="fa-solid:angry data-inline="false"></span>
> ```

Oh, my bad, that's interesting..

**Comment by GTANAdam** [comment]
Excuse me, any reason why this was closed without any comments?

**Comment by Scrum** [comment]
> @Scrum Excuse me, any reason why this was closed without any comments?

This task has been inactive for a very long time.  If this is still relevant for you, do not hesitate to re-open.
