### ISSUE TITLE
Is there a way to add my projects to the list ?

### ISSUE THREAD

**Issue by GoodManWEN** [vuejs/awesome-vue#3699]
Hi, recently I got a project that uses vue to simulate a linux gui in browser, since there isn't projects similar written in vue, it got some good reviews from the community and get several hundreds of stars on github.

I'm wondering if it's possible to add my project to this repo's list. Since I didn't find anything like a guideline, should I just raise a new PR directly? thanks.

**Comment by Jogai** [comment]
See .github folder.
