### ISSUE TITLE
Suggestion: Add Track Awesome List

### ISSUE THREAD

**Issue by theowenyoung** [vuejs/awesome-vue#3740]
Hi, @Scrum :

I'm Owen, a big fan of vuejs & awesome-vue. After discovering this awesome list, I read all kinds of interesting items in the entire list. After that, I wanted to see what updates were made to this list every once in a while, and had to go through Github's commit history to see what was updated for each commit. To be honest, it was quite a poor reading experience.

So for this need, I created [Track Awesome List](https://www.trackawesomelist.com) in my spare time, and created a profile for awesome-vue, https://www.trackawesomelist.com/vuejs/awesome-vue . With this link, we can read the latest updates of awesome-vue by day/week, free, daily updated. I wonder if anyone else has this need to see the latest updates, and if so, whether to add this link somewhere in the readme to tell others they can see the updates via this link?

I also created a badge for awesome-vue, which can also be linked to the timeline of awesome-vue.

[![Track Awesome List](https://www.trackawesomelist.com/badge.svg)](https://www.trackawesomelist.com/vuejs/awesome-vue)

```bash
[![Track Awesome List](https://www.trackawesomelist.com/badge.svg)](https://www.trackawesomelist.com/vuejs/awesome-vue)
```

Let me know what you think. I'm happy to receive any feedback or suggestions for improvement. I want this to be as useful as possible.

If you don’t think it’s necessary, that’s okay. I really appreciate you maintaining such an awesome list. I like this list.

**Comment by Scrum** [comment]
@theowenyoung Hi this is a good idea and implementation. I see no reason not to add it to the documentation and I will do it immediately.

**Comment by theowenyoung** [comment]
@Scrum Thanks! I hope this can help people like me.
