### ISSUE TITLE
Add Number of Repository Stars next to package

### ISSUE THREAD

**Issue by Kyriakos-Michael** [vuejs/awesome-vue#4036]
Add the Number of Repository Stars next to the package to easily compare usage and maintainability.

**Comment by Jogai** [comment]
Only issue is that Stars don't necessarily indicate usage and maintainability. Maybe last commit, and a graph of downloads each month?

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/awesome-vue/issues/2564
