### ISSUE TITLE
Add Quasar Framework to the list

### ISSUE THREAD

**Issue by rstoenescu** [vuejs/awesome-vue#439]
Hi,

I didn't know who to contact, so I opened this one here. Sorry if this is not the way to do it.
Main idea is that I think [Quasar Framework](http://quasar-framework.org/) deserves to be on the list.

What do you think?

Cheers,
Razvan Stoenescu

**Comment by miljan-aleksic** [comment]
As I can see, it's GitHub link It's already listed ;)

**Comment by rstoenescu** [comment]
Oh, my apologies. Last time I checked it wasn't and I thought I personally need to send someone a message to get it listed :)

Many thanks!

**Comment by miljan-aleksic** [comment]
You can always open a pull request, no need to ask anyone. It just somebody already did that. You can check the commits to see who, if curious.
