### ISSUE TITLE
Where to suggest new stuff to be shown on this repo's readme ?

### ISSUE THREAD

**Issue by ssouron** [vuejs/awesome-vue#545]
Is there a way to suggest new components, boilerplates, etc... to add here, or the only way is to contribute ? If this last case, where to ask to be contributor ?

Best regards, and thanks for your work.

**Comment by ssouron** [comment]
Or shall we fork the repo then make a pull request ?

**Comment by DannyFeliz** [comment]
As you said, you should make a pull request with your changes, just make sure you follow the [Contribution Guideline](https://github.com/vuejs/awesome-vue/blob/master/CONTRIBUTING.md)

**Comment by LinusBorg** [comment]
Yep, please for and send a PR.
