### ISSUE TITLE
Anything related to interactive data visualizations to be found?

### ISSUE THREAD

**Issue by aadamsx** [vuejs/awesome-vue#662]
Are there any libraries of composable Vue components for building interactive data visualizations?

**Comment by apertureless** [comment]
Well you could use chart.js which is rather for simple charts. [vue-chartjs](https://github.com/apertureless/vue-chartjs)

If you wan't something more complex, I would strongly recommend d3.
You can integrate it pretty easily into your vue environment. And generate many different visualisations based on your data.

**Comment by bernhardreiter** [comment]
Here is an example how to integrate d3: https://github.com/johnnynotsolucky/samples/tree/master/vuejs-d3

**Comment by brillout** [comment]
Feel free to re-open if you're still in need!
