### ISSUE TITLE
How to implement any awesome-vue in laravel 5.3?

### ISSUE THREAD

**Issue by vipin733** [vuejs/awesome-vue#704]
I try to install awesome-vue using NPM but I dont understand where I put the code any one could help me.
Any one suggest me a tutorial or where I start from scratch.

Thankk you

**Comment by happyDemon** [comment]
Why would you want that?
This repo is just an overview of Vue plugins.
What are you actually trying to get done?

**Comment by vipin733** [comment]
actually i want this in my laravel 5.3 using npm http://kzima.github.io/vuestrap-base-components
but I did not get how to do?

**Comment by happyDemon** [comment]
As the docs say, run the npm install in your laravel root dir.
in the JS file you should import the components you need and register them with vue.

copied from the site;
install:
`npm install vuestrap-base-components --save-dev`

import:
`import { vsAlert } from 'vuestrap-base-components/src/components'`

register:
*locally*
`new Vue({ components: { vsAlert }})`

*globally*
`Vue.component('vs-alert', vsAlert)`

these are basic concepts, I'd suggest reading up on ES6/ES2015 guides/tutorials and clear the vue docs(it's a great resource), maybe also read up on laravel elixir's docs for compiling (I think laracasts has a free course on Vue 1/2 you could follow)
