### ISSUE TITLE
[Youtube Video Tutorial Series]One Page App With Drupal 8 and Vue.js

### ISSUE THREAD

**Issue by kolier** [vuejs/awesome-vue#86]
[One Page App With Drupal 8 and Vue.js](https://www.youtube.com/playlist?list=PLUBR53Dw-Ef9Rr-bjMlosZclKLtPK4HhR)
https://www.youtube.com/playlist?list=PLUBR53Dw-Ef9Rr-bjMlosZclKLtPK4HhR

**Comment by yyx990803** [comment]
Thanks, please directly submit a Pull Request.
