### ISSUE TITLE
'vue-barcode' not added yet

### ISSUE THREAD

**Issue by amivit** [vuejs/awesome-vue#942]
https://github.com/lindell/vue-barcode

https://www.reddit.com/r/vuejs/comments/5ze7oh/vuebarcode_vue_component_for_barcode_generation/?utm_content=comments&utm_medium=hot&utm_source=reddit&utm_name=vuejs

**Comment by brillout** [comment]
Please make a PR. Would be nice if you can add a V2 support mention in the readme, GitHub tags are not shown on npm.
